Update Source

diff --git a/.github/diy/Source b/.github/diy/Source
--- a/.github/diy/Source
+++ b/.github/diy/Source
@@ -1,3 +1,60 @@
+git clone --depth 1 https://github.com/immortalwrt/homeproxy luci-app-homeproxy
 git clone --depth 1 https://github.com/jerrykuku/luci-theme-argon luci-theme-argon
 git clone --depth 1 https://github.com/jerrykuku/luci-app-argon-config luci-app-argon-config
 
+# 定义 clone_and_move 函数
+clone_and_move() {
+    temp_dir=$(mktemp -d) &&
+    git clone --depth 1 --branch "$1" "$2" "$temp_dir" &&
+    [ -d "$temp_dir/$3" ] && mv "$temp_dir/$3" "$4" || echo "Error: Subdirectory $3 not found."
+    rm -rf "$temp_dir"
+}
+
+# 定义 repos 数组
+repos=(
+    "main https://github.com/gdy666/luci-app-lucky luci-app-lucky ./luci-app-lucky"
+    "main https://github.com/nikkinikki-org/OpenWrt-nikki luci-app-nikki ./luci-app-nikki"
+    "main https://github.com/nikkinikki-org/OpenWrt-nikki nikki ./nikki"
+    "master https://github.com/vernesong/OpenClash luci-app-openclash ./luci-app-openclash"
+    "master https://github.com/immortalwrt/luci applications/luci-app-zerotier ./luci-app-zerotier"
+    "master https://github.com/immortalwrt/luci applications/luci-app-autoreboot ./luci-app-autoreboot"
+    "master https://github.com/immortalwrt/packages net/zerotier ./zerotier"
+    "master https://github.com/immortalwrt/packages libs/libnatpmp ./libnatpmp"
+    "master https://github.com/immortalwrt/packages net/miniupnpc ./miniupnpc"
+    "master https://github.com/immortalwrt/luci applications/luci-app-filebrowser ./luci-app-filebrowser"
+    "master https://github.com/immortalwrt/packages utils/filebrowser ./filebrowser"
+    # subconverter
+    "master https://github.com/immortalwrt/packages net/subconverter ./subconverter"
+    ## subconverter安装时需要的依赖
+    #"master https://github.com/immortalwrt/packages libs/libcron ./libcron"
+    #"master https://github.com/immortalwrt/packages libs/quickjspp ./quickjspp"
+    ## subconverter构建时需要的依赖（不必安装）
+    #"master https://github.com/immortalwrt/packages libs/jpcre2 ./jpcre2"
+    #"master https://github.com/immortalwrt/packages libs/rapidjson ./rapidjson"
+    #"master https://github.com/immortalwrt/packages libs/toml11 ./toml11"
+    # sub-web
+    "master https://github.com/immortalwrt/packages net/sub-web ./sub-web"   
+)
+
+# 遍历 repos 数组并调用 clone_and_move 函数
+for repo in "${repos[@]}"; do
+    IFS=' ' read -r branch repo_url repo_subdir target_dir <<< "$repo"
+    echo "Cloning repository: $repo_url (branch: $branch)..."
+    clone_and_move "$branch" "$repo_url" "$repo_subdir" "$target_dir"
+done
+
+# 更正 Makefile 内容
+sed -i \
+-e 's?include \.\./\.\./\(lang\|devel\)?include $(TOPDIR)/feeds/packages/\1?' \
+-e 's?2. Clash For OpenWRT?3. Applications?' \
+-e 's?\.\./\.\./luci.mk?$(TOPDIR)/feeds/luci/luci.mk?' \
+-e 's/ca-certificates/ca-bundle/' \
+-e 's/php7/php8/g' \
+-e 's/+docker /+docker +dockerd /g' \
+*/Makefile
+
+# 设置PKG_MIRROR_HASH:=skip FIXUP=1
+for package in subconverter sub-web; do
+    sed -i '/^PKG_MIRROR_HASH:=.*/c\PKG_MIRROR_HASH:=skip' "./${package}/Makefile"
+    sed -i '/^PKG_MIRROR_HASH:=skip/a FIXUP=1' "./${package}/Makefile"
+done
